#!/usr/bin/env python3
import glob
import argparse
import multiprocessing as mp
import re
import sys
import os, shutil, time, tempfile, signal, random, string
from datetime import datetime
from glob import glob
from enum import Enum, auto
from diopter.compiler import (
    CompilationSetting,
    CompilerExe,
    OptLevel,
    SourceProgram,
    Language,
)
from diopter.sanitizer import Sanitizer
from diopter.utils import TempDirEnv
import subprocess as sp
from dbconstructor.iogenerator.functioner import FunctionDB
from synthesize import Synthesizer
from dbconstructor.utils.compcert import CComp as this_CComp
from pathlib import Path

DEBUG = 0
"""CONFIG"""
NUM_MUTANTS = 10  # number of mutants generated by the synthesizer per seed.
COMPILER_TIMEOUT = 5

def find_riscv_vector_include():
    clang_path = sp.check_output(['which', 'clang'], text=True).strip()
    clang_root = os.path.dirname(os.path.dirname(clang_path))
    candidate_dirs = glob(os.path.join(clang_root, 'lib', 'clang', '*', 'include'))

    for inc_dir in candidate_dirs:
        if os.path.exists(os.path.join(inc_dir, 'riscv_vector.h')):
            return os.path.join(inc_dir, 'riscv_vector.h')

    raise FileNotFoundError("No path to include is found")

CC_ARGS = f"--target=riscv64-unknown-linux-gnu -march=rv64gcv -mabi=lp64d -menable-experimental-extensions -I{find_riscv_vector_include()} -w"

"""Global vars"""
WORK_DIR = "work"

class CompCode(Enum):
    """Compile status"""

    OK = auto()  # ok
    Timeout = auto()  # timeout during compilation
    Sanfail = auto()  # sanitization failed
    Crash = auto()  # compiler crash
    Error = auto()  # compiler error
    WrongEval = (
        auto()
    )  # inconsistent results across compilers but consistent within the same compiler
    Wrong = auto()  # inconsistent results across compilers/opts


def generate_random_string(len: int = 5) -> str:
    """Generate a random string of length len"""
    return "".join(
        random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits)
        for _ in range(len)
    )


def run_cmd(cmd, timeout):
    if type(cmd) is not list:
        cmd = cmd.split(" ")
        cmd = list(filter(lambda x: x != "", cmd))
    # Start the subprocess
    process = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.PIPE)
    # Wait for the subprocess to finish or timeout
    try:
        output, error = process.communicate(timeout=timeout)
        output = output.decode("utf-8")
    except sp.TimeoutExpired:
        # Timeout occurred, kill the process
        try:
            os.killpg(process.pid, signal.SIGTERM)
        except ProcessLookupError:
            pass
        finally:
            output = ""
        # A workaround to tmpxxx.exe as it sometimes escapes from os.killpg
        cmd_str = " ".join(cmd)
        if ".exe" in cmd_str:
            # Extract just the executable name to avoid pkill parameter conflicts
            exe_name = cmd_str.split()[-1]  # Get the last part which should be the .exe file
            if ".exe" in exe_name:
                os.system(f"pkill -9 -f '{exe_name}'")
        return 124, output

    # Return the exit code and stdout of the process
    return process.returncode, output


def write_bug_desc_to_file(to_file, data):
    with open(to_file, "a") as f:
        f.write(f"/* {data} */\n")

def compile_only(compiler, src):
    tmp_f = tempfile.NamedTemporaryFile(suffix=".exe", delete=False)
    tmp_f.close()
    exe = tmp_f.name
    cmd = f"{compiler} {src} {CC_ARGS} -o {exe}"
    ret, out = run_cmd(cmd, COMPILER_TIMEOUT)
    if ret == 124:  # another compile chance when timeout
        time.sleep(1)
        ret, out = run_cmd(cmd, COMPILER_TIMEOUT)
    if ret == 124:  # we treat timeout as crash now.
        write_bug_desc_to_file(src, f"Compiler timeout! Can't compile with {compiler}")
        if os.path.exists(exe):
            os.remove(exe)
        return CompCode.Timeout
    if ret != 0:
        write_bug_desc_to_file(src, f"Compiler crash! Can't compile with {compiler}")
        if os.path.exists(exe):
            os.remove(exe)
        return CompCode.Crash
    # Compilation successful, clean up and return OK
    if os.path.exists(exe):
        os.remove(exe)
    return CompCode.OK


def check_compile(src: str, compilers: list) -> CompCode:
    """Compile the program with a list of compilers and check for crashes only"""
    for comp in compilers:
        if DEBUG:
            print(
                datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
                "compile_only: ",
                comp,
                flush=True,
            )
        ret = compile_only(comp, src)
        if ret == CompCode.Crash:
            return CompCode.Crash
    return CompCode.OK


def run_one(
    compilers: list[str], save_wrong_dir: Path, SYNER: Synthesizer
) -> Path | None:
    """Run compiler testing"""
    # synthesize
    if DEBUG:
        print(
            datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
            "Start synthesizer",
            flush=True,
        )
    try:
        current_dir = Path.cwd() / WORK_DIR
        _, syn_files, _ = SYNER.synthesizer(dst_dir=current_dir)
    except Exception as e:
        print(f"SynthesizerError: {e}")
        return None
    src = syn_files[0]
    for syn_f in syn_files[1:]:
        print(f"Synthesized program {syn_f}", flush=True)
        ret = check_compile(syn_f, compilers)
        if ret == CompCode.Crash:
            rand_name = generate_random_string(8)
            case_dir = save_wrong_dir / f"case_{rand_name}"
            case_dir.mkdir(parents=True, exist_ok=True)
            crash_file = case_dir / "case.c"
            orig_file = case_dir / "orig.c"
            print(f"COMPILER CRASH FOUND: id {rand_name}\n", flush=True)
            shutil.copyfile(syn_f, crash_file.absolute().as_posix())
            shutil.copyfile(src, orig_file.absolute().as_posix())
            for syn_f in syn_files:
                os.remove(syn_f)
            return crash_file
    if DEBUG:
        print(
            datetime.now().strftime("%d/%m/%Y %H:%M:%S"), "End synthesizer", flush=True
        )
    for syn_f in syn_files:
        os.remove(syn_f)
    print("--------------------------")
    return None


def parse_compilers(compiler_config_file):
    with open(compiler_config_file, "r") as f:
        lines = f.readlines()
    compilers = []
    for line in lines:
        line = line.strip()
        if line == "":
            continue
        with tempfile.NamedTemporaryFile(suffix=".c", mode="w", delete=False) as tmp_f:
            tmp_f.write("int main() { return 0;}")
            tmp_f.close()
            test_compiler_cmd = f"{line} {tmp_f.name} -o /dev/null"
            ret, out = run_cmd(test_compiler_cmd, COMPILER_TIMEOUT)
            os.remove(tmp_f.name)
            if ret != 0:
                exit(f"cannot execute compiler {line}")
            else:
                compilers.append(line)
    return compilers


def fuzz_worker(worker_id: int, compilers: list[str], func_db: FunctionDB):
    save_dir = Path("bugs").resolve()
    save_dir.mkdir(parents=True, exist_ok=True)

    work_dir = Path(f"fuzz/work{worker_id}")
    work_dir.mkdir(parents=True, exist_ok=True)
    os.chdir(work_dir.absolute().as_posix())

    inner_work_dir = Path("work")
    inner_work_dir.mkdir(parents=True, exist_ok=True)
    for item in inner_work_dir.iterdir():
        if item.is_file():
            item.unlink()
        elif item.is_dir():
            shutil.rmtree(item)

    sys.stdout = open("log.txt", "w")
    sys.stderr = sys.stdout

    print(
        f"[{datetime.now().strftime('%Y-%m-%d %H:%M:%S')}] LegoFuzz starts", flush=True
    )

    SYNER = Synthesizer(
        func_database=func_db,
        prob=80,
        num_mutant=NUM_MUTANTS,
        iter=100,
        RAND=True,
        INLINE=False,
        DEBUG=DEBUG,
    )

    with TempDirEnv() as tmp_dir:
        os.environ["TMPDIR"] = tmp_dir.absolute().as_posix()
        while True:
            run_one(compilers, save_dir, SYNER)
            for p in tmp_dir.iterdir():
                p.unlink()


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="Let's LegoFuzz!")
    parser.add_argument(
        "--src",
        type=str,
        default="functions.jsonl",
        help="Path to function database file (default: functions.jsonl)",
    )
    parser.add_argument(
        "--cpu",
        type=int,
        default=mp.cpu_count(),
        help="Number of CPUs to run in parallel (default: all available cores)",
    )
    parser.add_argument(
        "--config",
        type=str,
        default="compilers.in",
        help="Path to compiler config file (default: ./compilers.in)",
    )
    args = parser.parse_args()

    if not os.path.exists(args.src):
        print(f"Error: Function database file '{args.src}' not found!")
        print("Please specify a valid database file with --src option.")
        sys.exit(1)

    compilers = parse_compilers(args.config)
    func_db = FunctionDB(args.src)  # Loaded once and forked (copy-on-write)

    processes = []
    for i in range(args.cpu):
        p = mp.Process(target=fuzz_worker, args=(i, compilers, func_db))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
